// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCJgEdBKKsuthHueRaIo5mct41qRlmadeQ',
    appId: '1:694751221829:android:8ea4d0dbaf914debcfab2c',
    messagingSenderId: '694751221829',
    projectId: 'courses-project-fcf06',
    storageBucket: 'courses-project-fcf06.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDu_YOaEWujffiMvttGE5EsEUAhTLxPPEQ',
    appId: '1:694751221829:ios:4cf5daf83430f7dfcfab2c',
    messagingSenderId: '694751221829',
    projectId: 'courses-project-fcf06',
    storageBucket: 'courses-project-fcf06.appspot.com',
    iosBundleId: 'com.example.authenticationTask',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCFVaE-S2DGfqVl9gINJxc1ViJ0MNriHlQ',
    appId: '1:694751221829:web:01361290c95c9f0fcfab2c',
    messagingSenderId: '694751221829',
    projectId: 'courses-project-fcf06',
    authDomain: 'courses-project-fcf06.firebaseapp.com',
    storageBucket: 'courses-project-fcf06.appspot.com',
    measurementId: 'G-5ZM6GFJV03',
  );
}
